language: julia
os:
    - linux
julia:
    - 0.5
    - nightly
addons:
  apt:
    packages:
      - texlive-full

notifications:
    email: false
script:
     - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
     - julia -e 'Pkg.clone(pwd())'
     - julia -e src/simple.jl
     - make -C report travis
